{
 "title": "Timberborn Realtime Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Beavers & Bots",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "timberborn_total_beavers{job=\"timberborn\"}",
     "legendFormat": "Beavers Total"
    },
    {
     "expr": "timberborn_total_bots{job=\"timberborn\"}",
     "legendFormat": "Bots Total"
    }
   ]
  },
  {
   "title": "Total Beaver Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "timberborn_total_beavers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Bot Count",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "timberborn_total_bots", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Citizen Distribution",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "timberborn_adult_beavers", "legendFormat": "Adult Beavers" },
    { "expr": "timberborn_child_beavers", "legendFormat": "Child Beavers" },
    { "expr": "timberborn_total_bots", "legendFormat": "Bots" }
   ]
  },
  {
   "title": "Science Points",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    { "expr": "timberborn_science_points", "legendFormat": "Science" }
   ]
  },
  {
   "title": "Water in Stock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "timberborn_goods_stock{good=\"water\"}",
     "legendFormat": "Water in Stock"
    },
    {
     "expr": "timberborn_goods_capacity{good=\"water\"}",
     "legendFormat": "Water Storage Capacity"
    }
   ]
  },
  {
   "title": "Goods In Stock",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    { "expr": "timberborn_goods_stock", "legendFormat": "{{good}}" }
   ]
  },
  {
   "title": "Capacity of all Goods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "targets": [
    { "expr": "timberborn_goods_capacity", "legendFormat": "{{good}}" }
   ]
  }
 ]
}