global:
  scrape_interval: 2s
  evaluation_interval: 2s
  external_labels:
    monitor: 'monitor'

scrape_configs:
  - job_name: 'timberborn'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets:
          - host.docker.internal:8000